- source/_templates/layout.html
@jakereps or @thermokarst, can one of you review/merge?
> Add Google Analytics tracking

- source/tutorials/fmt.rst
- source/tutorials/moving-pictures.rst
@jakereps or @thermokarst, can one of you review/merge please?
> Fix broken RST for nested lists in tutorials

- .travis.yml
- README.md
- publish-assets/index.html
- requirements.txt
> Add S3 publishing instructions to README.md

- source/tutorials/import-sequence-data.rst
- source/tutorials/import.rst
- source/tutorials/index.rst
fixes #33 
I debated merging this tutorial with the existing *Importing* tutorial, but I see this one expanding a lot as we support additional input formats so it seems to make more sense on its own. Any objections to that?
> adds importing sequence data tutorial

- source/sphinx_directives/command_block.py
> ENH: Allow multiline command blocks

- source/tutorials/fmt.rst
- source/tutorials/import-sequence-data.rst
- source/tutorials/import.rst
- source/tutorials/moving-pictures.rst
- source/tutorials/table-filtering.rst
Resolves #38 
Pending merge of #43
> MAINT: Update Tutorials for multiline support

- source/plugins/developing.rst
Related to: qiime2/cookiecutter-plugin-template/issues/10
> ENH: Add note about cache-busting

- source/theme/static/style.css
> ENH: Unhide links in admonitions

- source/_templates/layout.html
- source/theme/static/style.css
> MAINT: Enclose footer in main wrapper

- source/theme/static/style.css
> MAINT: Widen main container

- source/tutorials/importing.rst
The URLs to be downloaded don't exist yet, but I have the files locally and I've tested the import commands.
> DOC: adds importing of paired-end data

- source/tutorials/feature-classifier.rst
- source/tutorials/moving-pictures.rst
Based on @BenKaehler's commits in https://github.com/qiime2/docs/pull/69
Pair-programmed with @thermokarst.
> ENH: Updated feature-classifier tutorial for 2017.2 release

- source/tutorials/atacama-soils.rst
This now covers only paired-end relevant commands and uses a smaller data set to optimize runtime.
> ENH: update atacama tutorial 

- source/_static/bootstrap-dropdown.js
- source/_static/external-links.js
- source/_templates/layout.html
- source/theme/static/style.css
> ENH: version-switcher and style cleanup

- source/_templates/layout.html
| before  | after  | 
|---|---|
|![image](https://cloud.githubusercontent.com/assets/2638727/22716320/b665a016-ed52-11e6-916b-7deb301805ec.png) | ![image](https://cloud.githubusercontent.com/assets/2638727/22716314/b1e0b4f4-ed52-11e6-8496-6e6d4eaeb6b0.png)  |
> MAINT: Swap justification of version dropdown

- source/getting-started.rst
- source/install/index.rst
- source/install/native.rst
- source/install/virtual/index.rst
- source/interfaces/q2cli.rst
- source/tutorials/index.rst
> ENH: new install, q2cli, and distribution docs for 2017.2

- source/data-resources.rst
- source/install/virtual/aws.rst
- source/tutorials/atacama-soils.rst
- source/tutorials/feature-classifier.rst
- source/tutorials/filtering.rst
- source/tutorials/fmt.rst
- source/tutorials/importing.rst
- source/tutorials/moving-pictures.rst
Waiting until @gregcaporaso can provide final names on the classifiers.
> MAINT: update URLS

- source/sphinx_extensions/command_block/extension.py
This replaces the use of `self.error` in the `command_block` extension
to use Sphinx-defined exceptions instead. This bug was revealed during
testing, where subprocess commands that were returning non-zero exit
codes were inconsistently raising exceptions or passing silently.
> BUG: Docutils exceptions not consistently handled

- source/interfaces/q2studio.rst
> MAINT: Add note about conda env to q2studio launch

- source/tutorials/feature-classifier.rst
- source/tutorials/moving-pictures.rst
Won't work until qiime/q2-feature-classifier#62 is merged.
> ENH: updated for qiime/q2-feature-classifier#62

- .travis.yml
- README.md
- source/data-resources.rst
- source/install/index.rst
- source/install/native.rst
- source/install/virtual/aws.rst
- source/install/virtual/docker.rst
- source/install/virtual/virtualbox.rst
- source/interfaces/q2studio.rst
- source/tutorials/atacama-soils.rst
- source/tutorials/exporting.rst
- source/tutorials/feature-classifier.rst
- source/tutorials/filtering.rst
- source/tutorials/fmt.rst
- source/tutorials/importing.rst
- source/tutorials/moving-pictures.rst
- source/upgrade.rst
This should be everything. Done thanks to grep and vim's quickfix menu.
> REL: updates for 2017.4

- source/tutorials/atacama-soils.rst
- source/tutorials/filtering.rst
- source/tutorials/fmt.rst
- source/tutorials/moving-pictures.rst
This would depend on https://github.com/qiime2/q2-feature-table/pull/105 being merged.
> DOC: Update to use recent parameter name changes

- source/tutorials/feature-classifier.rst
- source/tutorials/moving-pictures.rst
There was a small interface change in qiime2/q2-feature-classifier#69 that requires a change to the `feature-classifier` tutorial.
DO NOT MERGE until qiime2/q2-feature-classifier#69 has been merged.
> ENH: updated to reflect qiime2/q2-feature-classifier#69

- source/tutorials/atacama-soils.rst
- source/tutorials/fmt.rst
- source/tutorials/moving-pictures.rst
> BUG: revert changes to summarize in docs

- source/tutorials/filtering.rst
Dependent on https://github.com/qiime2/q2-diversity/pull/103
> DOC:Updates parameter name changes in q2-diversity

- source/install/virtual/aws.rst
- source/install/virtual/virtualbox.rst
Questions for reviewer:
How do we feel about the following URLs?
https://data.qiime2.org/distro/core/aws-amis.txt
https://data.qiime2.org/distro/core/virtualbox-images.txt
> MAINT: Update VM install language to split out DLs

- source/data-resources.rst
- source/install/index.rst
- source/install/native.rst
- source/install/virtual/docker.rst
- source/install/virtual/virtualbox.rst
- source/interfaces/q2studio.rst
- source/tutorials/atacama-soils.rst
- source/tutorials/exporting.rst
- source/tutorials/feature-classifier.rst
- source/tutorials/filtering.rst
- source/tutorials/fmt.rst
- source/tutorials/importing.rst
- source/tutorials/moving-pictures.rst
- source/upgrade.rst
Blocked by https://github.com/qiime2/data.qiime2.org/pull/16
> MAINT: Version bump (2017.6)

- source/install/index.rst
- source/tutorials/index.rst
- source/tutorials/metadata.rst
- source/tutorials/moving-pictures.rst
This tutorial won't build until a PR addressing https://github.com/qiime2/q2cli/issues/140 is merged.
> ENH: adds metadata tutorial

- source/tutorials/moving-pictures.rst
Fixes #161
Note to reviewer --- take a look at [this summary](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fdocs.qiime2.org%2F2017.6%2Fdata%2Ftutorials%2Fmoving-pictures%2Ftable.qzv) and see if this sampling depth makes sense for the tutorial. I chose this depth to minimize changes to the text (seems like at this depth no text needs to change, just the cutoff Sample ID). Thanks!
> MAINT/BUG: Updating MP sampling-depth suggestions

- source/interfaces/q2studio.rst
> ENH: Make q2studio env activate instructions clear

- source/install/native.rst
- source/interfaces/q2studio.rst
- source/sphinx_extensions/command_block/templates/download.html
- source/theme/static/style.css
> UX BUG: Native install (mac vs linux)

- source/install/native.rst
> ENH: conda clean tip

- Makefile
- source/sphinx_extensions/command_block/extension.py
Just hacked this in because it was faster than waiting for `make html` when testing the gneiss tutorial.
Feel free to close or request any changes. Works great though!
> ENH: adds DEBUG variable for make preview

- source/tutorials/moving-pictures.rst
Do not merge until #193 is merged. (I'll rebase or open a new PR when that happens)
Ready for review otherwise (skip the first commit)
> Adds ancom to moving pictures tutorial

- source/data-resources.rst
- source/install/index.rst
- source/install/native.rst
- source/install/virtual/docker.rst
- source/install/virtual/virtualbox.rst
- source/interfaces/q2studio.rst
- source/tutorials/atacama-soils.rst
- source/tutorials/exporting.rst
- source/tutorials/feature-classifier.rst
- source/tutorials/filtering.rst
- source/tutorials/fmt.rst
- source/tutorials/gneiss.rst
- source/tutorials/importing.rst
- source/tutorials/longitudinal.rst
- source/tutorials/metadata.rst
- source/tutorials/moving-pictures.rst
- source/tutorials/sample-classifier.rst
Note to merger, please rebase and merge, we want to keep both logical commits. Thanks!
> ENH: stop exec'ing q2studio / REL: 2017.9.0.dev0

- source/tutorials/longitudinal.rst
DO NOT MERGE: pending [this PR](https://github.com/qiime2/q2-longitudinal/pull/55)
> added tutorial for longitudinal nmit

- source/tutorials/atacama-soils.rst
- source/tutorials/fmt.rst
- source/tutorials/moving-pictures.rst
Waiting on https://github.com/qiime2/q2-diversity/pull/147
> MAINT: Tutorials use core-metrics-phylogenetic

- source/tutorials/fmt.rst
> added longitudinal questions and removed note about feature parity

- source/tutorials/moving-pictures.rst
> BUG: correct deblur doc

- source/tutorials/gneiss.rst
This reflects the changes in the `balance-taxonomy` command.  See [here](https://github.com/qiime2/q2-gneiss/pull/17) for more details.
The tutorial has been run through and I have verified that these new command work.
> ENH: modifying balance-taxonomy command in light of new changes

- source/tutorials/filtering.rst
Fixes #163 
This depends on the following PRs (UPDATE: both are merged now):
* https://github.com/qiime2/data.qiime2.org/pull/37
* https://github.com/qiime2/q2-taxa/pull/98
> ENH: adds taxonomy-based filtering to filtering data tutorial

- source/data-resources.rst
Related to changes in https://github.com/qiime2/q2-feature-classifier/pull/95
> MAINT: Retrained classifiers for sklearn 0.19.1

- source/tutorials/longitudinal.rst
> q2-longitudinal tutorial: add information on identifying valid metrics

- source/community.rst
> community page: point users to forum for bug reports, feedback, etc

- source/tutorials/feature-classifier.rst
> fixed Mismatched trunc-len between tutorials

- source/tutorials/longitudinal.rst
fixes #230 
Also includes a few other updates to the q2-long tutorial for the 2017.11 release. I made those changes in this PR to avoid merge conflicts.
DO NOT MERGE until [this PR](https://github.com/qiime2/q2-longitudinal/pull/62) is merged in q2-long (to add support for spaghetti plots, which I've documented here on the assumption that it'll make it in this release).
> q2-longitudinal tutorial: linear-mixed-effects results description and other updates

- source/tutorials/moving-pictures.rst
> MAINT: Updating quality-filter stats viz

- source/tutorials/fmt.rst
depends on https://github.com/qiime2/q2-feature-table/pull/157
> MAINT: update merge methods

- source/tutorials/metadata.rst
I built and reviewed the docs locally to test these changes.
> MAINT: minor edits

- source/tutorials/metadata.rst
Updated metadata spec to match implementation: https://github.com/qiime2/qiime2/pull/364
> MAINT: update metadata spec to remove case-insensitive duplicates check

- source/tutorials/chimera.rst
- source/tutorials/index.rst
> MAINT: Port vsearch/chimera community tutorial

- source/tutorials/index.rst
- source/tutorials/read-joining.rst
Fixes #269 
---
If we decide to keep the links to the outstanding issues in this tutorial (see below), when we merge this, lets update those issues with reminders to update this tutorial when those changes are made.
> MAINT: Port read-joining tutorial

- source/tutorials/moving-pictures.rst
Depends on qiime2/q2-emperor#57
> ENH: Update parameter name

- source/conf.py
- source/install/native.rst
> MAINT: Update install guide; New copyright year

- source/tutorials/feature-classifier.rst
fixes #262 
fixes #263 
fixes #216 
related to #202 insofar as training of ITS data is briefly discussed.
> feature-classifier tutorial: add notes on PE, extraction, and ITS

- source/interfaces/artifact-api.rst
> DOC: remove uninstall from artifact API tutorial

- source/tutorials/exporting.rst
> DOC: Update exporting tutorial to match new q2cli changes

- source/tutorials/exporting.rst
- source/tutorials/feature-classifier.rst
- source/tutorials/importing.rst
- source/tutorials/read-joining.rst
Depends on this [PR](https://github.com/qiime2/q2cli/pull/195) from q2cli.
Fixes #321
> DOC: Update docs to reflect API changes in import/extract

- source/interfaces/artifact-api.rst
Currently the API tutorial mentions metadata, but the only use of it in
the tutorial is in a command line call. This should help clarify the
loading of and usage of metadata in the qiime2 API
> DOC: Added metadata example

- source/tutorials/otu-clustering.rst
> BUG: Fixed typo in OTU-Clustering tutorial

- source/tutorials/sample-classifier.rst
the first steps on #329 
depends on https://github.com/qiime2/q2-sample-classifier/pull/116/
will keep busywork from breaking while I set to work on #329 proper
> q2-sample-classifier update outputs

- source/data-resources.rst
Fixes #306 
---
SILVA 132, as well as new defaults specified in q2-feature-classifier.
> MAINT: update pre-trained classifiers

- source/tutorials/moving-pictures.rst
Reflects the new pipeline added [here](https://github.com/qiime2/q2-phylogeny/pull/49).
> ENH: Update docs with new phylogeny pipeline tutorial

- source/tutorials/sample-classifier.rst
depends on https://github.com/qiime2/q2-sample-classifier/pull/117/
> updated maturity tutorial to use pipeline

- source/install/native.rst
closes https://github.com/qiime2/docs.qiime2.org/issues/18
> add 'upgrade by installing again' to native.rst

- source/tutorials/longitudinal.rst
added feature-volatility to tutorial and fixed maturity-index tutorial (to link to sample-classifier tutorial as appropriate, e.g., replacing "as described above" statements)
> added feature-volatility to tutorial and fixed maturity-index tutorial

- source/tutorials/sample-classifier.rst
Added link to q2-sample-classifier API docs from the tutorial
> q2-sample-classifier tutorial: link to API docs

- source/tutorials/fmt-cdiff.rst
main changes:
- adding filter example
- adding study design
- fixing some old text left behind
> add filter to cdiff fmt tutorial, fix some text

- source/tutorials/atacama-soils.rst
> Small typo fix

- source/tutorials/qiime2-for-experienced-microbiome-researchers.rst
PR for patch requested in #345 : ([comment](https://github.com/qiime2/docs/pull/345#issuecomment-437708336)).
> Remove missing doc page comments

- source/tutorials/overview.rst
renamed the "QIIME 2 for dummies" part in case readers are not familiar with the phrase/book titles.
also added some headings to help organize
also added a link to the experienced user overview tutorial
> overview tutorial tweaks

- source/tutorials/fmt-cdiff.rst
Removes a ToDo in the tutorial. Happy to create an issue in its place of course if reviewers prefer that.
> Remove a ToDO

- source/tutorials/atacama-soils.rst
Updates to use final data citation rather than _in review_ citation. I also modified so only the title is italicized.
> MAINT: update to final data citation

- source/tutorials/fmt-cdiff.rst
> BUG: change version for classifier download

- source/install/native.rst
> BUG: Inline wget workaround

- source/citation.rst
- source/index.rst
Added a page listing the citation for QIIME 2 (currently the pre-print), and information on listing citation information associated with plugins, artifacts, and individual files.
> added QIIME 2 citations page

- source/tutorials/sample-classifier.rst
blocked by: https://github.com/qiime2/q2-sample-classifier/pull/147
added an example using `sample-classifier heatmap`
> importance features heatmap

- source/tutorials/atacama-soils.rst
- source/tutorials/filtering.rst
- source/tutorials/moving-pictures.rst
- source/tutorials/sample-classifier.rst
> MAINT: No more QIIME 1-esque MD columns

- source/tutorials/sample-classifier.rst
Replaced producted with produced.
---
> found typo

- source/tutorials/sample-classifier.rst
Changed an to a and moved (inevitably incomplete) and added though. Obviously, there are other ways to fix this other than my suggestion. Feel free to change it in a different way. It is just technically incorrect because it is saying "an" list as opposed to "a" list.
---
> found another typo

- source/sphinx_extensions/command_block/extension.py
- source/tutorials/pd-mice.rst
Usage:
```sphinx
.. command-block::
:stdout:
qiime tools --help
```
Results:
I did not end up coloring the stderr red.
> IMP: Capture command streams

- source/sphinx_extensions/command_block/extension.py
This code was originally written by @ebolyen
> MAINT: command-block - handle result overwriting

- source/sphinx_extensions/command_block/extension.py
> IMP: Support multi-command streamed blocks

- source/tutorials/sample-classifier.rst
ready to review but DNM
blocked by https://github.com/qiime2/q2-sample-classifier/pull/159
tests pass locally in DEBUG mode
> added class probabilities and ROC to sample-classifier tutorial

- source/tutorials/importing.rst
Related to https://github.com/qiime2/q2-types/pull/223
> MAINT: drop BIOM v1.0.0

- source/tutorials/pd-mice.rst
- source/tutorials/sample-classifier.rst
Added a clawback section to the pd-mice tutorial. For use in upcoming workshop in Bangkok, September 2019.
Thanks @nbokulich for editorial services.
> ENH: added clawback section to pd-mice tutorial

- source/tutorials/moving-pictures.rst
> ENH: adds `qiime tools peek` to MP tutorial

- source/tutorials/importing.rst
closes #452 
Please forgive any typos/misformatting. I've been unable to conda install sphinx so far, which is preventing me from previewing the docs.
> ENH: Importing tut. adds multiplexed barcode in sequence section

- source/install/index.rst
- source/install/native.rst
> ENH: Protocols paper updates

- source/tutorials/read-joining.rst
> MAINT: read joining tutorial manifest fmt

- source/data-resources.rst
- source/install/index.rst
- source/install/native.rst
- source/install/virtual/docker.rst
- source/install/virtual/virtualbox.rst
- source/interfaces/q2studio.rst
- source/tutorials/atacama-soils.rst
- source/tutorials/chimera.rst
- source/tutorials/exporting.rst
- source/tutorials/feature-classifier.rst
- source/tutorials/filtering.rst
- source/tutorials/fmt.rst
- source/tutorials/gneiss.rst
- source/tutorials/importing.rst
- source/tutorials/longitudinal.rst
- source/tutorials/metadata.rst
- source/tutorials/moving-pictures.rst
- source/tutorials/otu-clustering.rst
- source/tutorials/overview.rst
- source/tutorials/pd-mice.rst
- source/tutorials/phylogeny.rst
- source/tutorials/quality-control.rst
- source/tutorials/read-joining.rst
- source/tutorials/sample-classifier.rst
- source/tutorials/utilities.rst
Nothing to see here... Just bumping from 2020.5 to 2020.6, since we postponed the next release by a month ([link](https://forum.qiime2.org/t/preview-qiime-2-2020-6-development-changelog/13906/2?u=thermokarst))
> MAINT: bump to 2020.6

- source/tutorials/utilities.rst
Fixes #458 
@andrewsanchez , is this more or less what you were looking for?
> Documents difference between view tool and q2view

- source/tutorials/atacama-soils.rst
This PR represents two logical commits that should be preserved, please rebase and merge when this PR is accepted.
1. c346e6b: Line-wrapping
1. b80f024: Adding new pre-processing steps
> Atacama QOL && new filtering/subsampling sections

- source/install/index.rst
> MAINT: adds diversity-lib to install index

- source/interfaces/artifact-api.rst
Oops! I failed to save `artifact-api.rst` before committing last night. These  `observed_otus->observed_features` changes should have made it into #482 .
> MAINT: observed_otus->observed_features in artifact-api.rst

- source/interfaces/q2studio.rst
See #497 for details.  closes #497
> Install gevent and nodejs with conda.

- source/tutorials/read-joining.rst
closes #503.  See #503 for details.
> Update read joining tutorial.

- requirements.txt
> debug: remove Sphinx restriction and Jinja2 < 3.0

- source/tutorials/otu-clustering.rst
> MAINT: OTU clustering tutorial - closed-ref description is inaccurate

- source/index.rst
- source/jupyter-book-tutorials.rst
Adding page that includes q2book and LIAO (Cancer Microbiome Intervention) tutorial
> IMP: Adding page for Jupyter Book Tutorials

- source/conf.py
Fixes https://busywork.qiime2.org/teams/main/pipelines/master-distribution/jobs/integration/builds/480
> CONF: update language

- source/tutorials/utilities.rst
The [utilities tutorial](https://docs.qiime2.org/2021.8/tutorials/utilities/#artifact-api) has been missing an Artifact API section for a bit now, so I knocked something together while trying to get more familiar with the API. I'm sure there are plenty of things I've mixed up or overlooked here, so don't be shy when reviewing.
> Adds artifact API section to tutorials/utilities

- source/data-resources.rst
- source/install/index.rst
- source/install/native.rst
- source/install/virtual/docker.rst
- source/install/virtual/virtualbox.rst
- source/interfaces/q2studio.rst
- source/tutorials/atacama-soils.rst
- source/tutorials/chimera.rst
- source/tutorials/exporting.rst
- source/tutorials/feature-classifier.rst
- source/tutorials/filtering.rst
- source/tutorials/fmt.rst
- source/tutorials/gneiss.rst
- source/tutorials/importing.rst
- source/tutorials/longitudinal.rst
- source/tutorials/metadata.rst
- source/tutorials/moving-pictures-usage.rst
- source/tutorials/moving-pictures.rst
- source/tutorials/otu-clustering.rst
- source/tutorials/overview.rst
- source/tutorials/pd-mice.rst
- source/tutorials/phylogeny.rst
- source/tutorials/qiime2-for-experienced-microbiome-researchers.rst
- source/tutorials/quality-control.rst
- source/tutorials/read-joining.rst
- source/tutorials/sample-classifier.rst
- source/tutorials/utilities.rst
This is a delayed version bump for the docs since we never had a 2022.4 release
> dev-bump: 2022.8

- source/interfaces/artifact-api.rst
Improving the readability of Artifact API documentation, in order to make it more accessible
> DOC: improve Artifact API documentation

- source/data-resources.rst
Paired with [this PR](https://github.com/qiime2/data302/pull/141)
> NEW: updates GG classifier links to AWS URLs

- source/data-resources.rst
This PR updates the URL and reference for Greengenes2 to reflect its peer reviewed publication.
> DOC: reflect published greengenes2 manuscript

- source/glossary.rst
This PR adds rarefy and rarefaction definitions to the glossary.  Ref: https://www.biorxiv.org/content/10.1101/2023.06.23.546312v1.full
> IMP: add rarefy and rarefaction definition to glossary

- source/conf.py
- source/data-resources.rst
- source/install/index.rst
- source/install/native.rst
- source/install/virtual/docker.rst
- source/tutorials/atacama-soils.rst
- source/tutorials/chimera.rst
- source/tutorials/exporting.rst
- source/tutorials/feature-classifier.rst
- source/tutorials/filtering.rst
- source/tutorials/fmt.rst
- source/tutorials/importing.rst
- source/tutorials/longitudinal.rst
- source/tutorials/metadata.rst
- source/tutorials/moving-pictures-usage.rst
- source/tutorials/moving-pictures.rst
- source/tutorials/otu-clustering.rst
- source/tutorials/overview.rst
- source/tutorials/pd-mice.rst
- source/tutorials/phylogeny.rst
- source/tutorials/qiime2-for-experienced-microbiome-researchers.rst
- source/tutorials/quality-control.rst
- source/tutorials/read-joining.rst
- source/tutorials/sample-classifier.rst
- source/tutorials/utilities.rst
also updates copyright year for 2024
> dev-bump: 2024.2

- source/data-resources.rst
- source/install/index.rst
- source/install/native.rst
- source/install/virtual/docker.rst
- source/tutorials/atacama-soils.rst
- source/tutorials/chimera.rst
- source/tutorials/exporting.rst
- source/tutorials/feature-classifier.rst
- source/tutorials/filtering.rst
- source/tutorials/fmt.rst
- source/tutorials/importing.rst
- source/tutorials/longitudinal.rst
- source/tutorials/metadata.rst
- source/tutorials/moving-pictures-usage.rst
- source/tutorials/moving-pictures.rst
- source/tutorials/otu-clustering.rst
- source/tutorials/overview.rst
- source/tutorials/pd-mice.rst
- source/tutorials/phylogeny.rst
- source/tutorials/qiime2-for-experienced-microbiome-researchers.rst
- source/tutorials/quality-control.rst
- source/tutorials/read-joining.rst
- source/tutorials/sample-classifier.rst
- source/tutorials/utilities.rst
`vsearch merge-pairs` API was changed [here](https://github.com/qiime2/q2-vsearch/pull/95), which also needs to be updated in the docs commands to prevent doc build failures.
> BUG: adding vsearch merge-pairs API change

- source/data-resources.rst
Replace the classifier stuff in the docs with a link to https://resources.qiime2.org
> Remove classifier text and replace with external link

- source/data-resources.rst
- source/install/index.rst
- source/install/native.rst
- source/install/virtual/docker.rst
- source/tutorials/atacama-soils.rst
- source/tutorials/chimera.rst
- source/tutorials/exporting.rst
- source/tutorials/feature-classifier.rst
- source/tutorials/filtering.rst
- source/tutorials/fmt.rst
- source/tutorials/importing.rst
- source/tutorials/longitudinal.rst
- source/tutorials/metadata.rst
- source/tutorials/moving-pictures-usage.rst
- source/tutorials/moving-pictures.rst
- source/tutorials/otu-clustering.rst
- source/tutorials/overview.rst
- source/tutorials/pd-mice.rst
- source/tutorials/phylogeny.rst
- source/tutorials/qiime2-for-experienced-microbiome-researchers.rst
- source/tutorials/quality-control.rst
- source/tutorials/read-joining.rst
- source/tutorials/sample-classifier.rst
- source/tutorials/utilities.rst
trying again in a fresh PR (need the updates to ci.yml to be reflected in `verify`)
> dev-bump: 2024.10

- source/data-resources.rst
- source/glossary.rst
- source/install/index.rst
- source/install/native.rst
- source/install/virtual/docker.rst
- source/install/virtual/index.rst
- source/tutorials/atacama-soils.rst
- source/tutorials/chimera.rst
- source/tutorials/exporting.rst
- source/tutorials/feature-classifier.rst
- source/tutorials/filtering.rst
- source/tutorials/fmt.rst
- source/tutorials/importing.rst
- source/tutorials/longitudinal.rst
- source/tutorials/metadata.rst
- source/tutorials/moving-pictures-usage.rst
- source/tutorials/moving-pictures.rst
- source/tutorials/otu-clustering.rst
- source/tutorials/overview.rst
- source/tutorials/pd-mice.rst
- source/tutorials/phylogeny.rst
- source/tutorials/qiime2-for-experienced-microbiome-researchers.rst
- source/tutorials/quality-control.rst
- source/tutorials/read-joining.rst
- source/tutorials/sample-classifier.rst
- source/tutorials/utilities.rst
* renames shotgun distro --> metagenome
* updates plugin list (for both amplicon and metagenome distros), as this was out of date.
> MAINT: rename shotgun->metagenome and update plugin list

- source/data-resources.rst
- source/install/native.rst
paired with https://github.com/qiime2/data302/pull/156
> MAINT: sepp-ref DB URLs & data302 URLs for env install

- source/tutorials/metadata.rst
fixes https://github.com/qiime2/docs/issues/577
This was also addressed for the new user docs (coming soon!) in https://github.com/caporaso-lab/using-qiime2/pull/3.
> add note about case insensitivity of column names

- .github/workflows/ci.yml
- source/conf.py
- source/data-resources.rst
- source/install/index.rst
- source/install/native.rst
- source/install/virtual/docker.rst
- source/tutorials/atacama-soils.rst
- source/tutorials/chimera.rst
- source/tutorials/exporting.rst
- source/tutorials/feature-classifier.rst
- source/tutorials/filtering.rst
- source/tutorials/fmt.rst
- source/tutorials/importing.rst
- source/tutorials/longitudinal.rst
- source/tutorials/metadata.rst
- source/tutorials/moving-pictures-usage.rst
- source/tutorials/moving-pictures.rst
- source/tutorials/otu-clustering.rst
- source/tutorials/overview.rst
- source/tutorials/pd-mice.rst
- source/tutorials/phylogeny.rst
- source/tutorials/qiime2-for-experienced-microbiome-researchers.rst
- source/tutorials/quality-control.rst
- source/tutorials/read-joining.rst
- source/tutorials/sample-classifier.rst
- source/tutorials/utilities.rst
> DEV BUMP 2024.10 TAKE 3

- source/install/index.rst
plugin/distro updates for 2025.4
> MAINT: update listed plugins for each distro in 2025.4
