source/_templates/layout.html, source/theme/static/style.css
Docs site tweaks for 2.0.6 site
=> ENH: Various tweaks to new theme style

Makefile, source/_templates/layout.html
Also, reformatted Makefile serve command for easier copy/paste.
=> Use relative link instead of harcoded docs.qiime2.org for logo href

README.md
Static S3 sites need public read on all objects.
=> Add `--acl public-read` flag to publishing commands

source/tutorials/table-filtering.rst
`make html` fails when running the commands in the table filtering tutorial because each command overwrites the output .qza from the previous command. The `commandblock` directive disallows output overwriting because only a single .qza link can be provided for each output .qza, making it impossible to link to each "version" of the .qza.
=> BUG: avoid overwriting output .qza files in table filtering tutorial

source/interfaces/artifact-api.rst, source/tutorials/fmt.rst, source/tutorials/import-sequence-data.rst, source/tutorials/import.rst, source/tutorials/moving-pictures.rst, source/tutorials/table-filtering.rst
Tested this locally with `make html`.
Fixes #41.
=> ENH: use explicit .qza/.qzv extension in command outputs

source/data-resources.rst, source/install/native.rst, source/interfaces/artifact-api.rst, source/plugins/developing.rst
Also updates conda install commands to specify ``--override-channels`` and ``-c defaults`` to avoid issues with channels in ``.condarc``.
See related discussion in https://github.com/qiime2/q2-dada2/issues/13
=> ENH: install latest dada2 via Bioconductor

source/tutorials/filtering.rst, source/tutorials/index.rst
Added examples of filtering distance matrices to the table filtering tutorial. Renamed and restructured tutorial to be more general (there are now sections for feature tables and distance matrices).
New URL will be https://docs.qiime2.org/2017.2/tutorials/filtering/
=> ENH: distance matrix filtering tutorial

source/conf.py, source/sphinx_extensions/command_block/extension.py
We want the train release version (i.e. 2017.2) in URLs instead of the exact version (e.g. 2017.2.0).
=> MAINT: use train release version to version docs

source/plugins/developing.rst
Removes `qiime dev plugin-init` instructions in favor of using Cookiecutter directly.
=> ENH: add Cookiecutter instructions to plugin dev docs

source/sphinx_extensions/plugin_directory/templates/available.rst, source/sphinx_extensions/plugin_directory/templates/plugin.rst
Added automatic sphinx handling of `description` and `short_description` per issue [#120](https://github.com/qiime2/docs/issues/120#issuecomment-285428117).
See below screenshots:
**Plugins page**
Note that if no `short_description` exists for the plugin then I just show the name of the plugin.  If a short description exists, I append `: short_description` to the title of the item in the `.doctree`.
**Available Plugins page**
Note that the approach taken on the plugins page as described above automatically propagates to this page.
**feature-table page**
Note the implementation of the `description` parameter in the table of values, per the suggestion in the referenced issue.  Let me know if you'd like this tweaked in any particular way.
**types page**
Currently if no `short_description` …
=> Plugin descriptions

source/tutorials/importing.rst
Addresses #118. 
The 2017.2 data urls for this tutorial are `2017.2/tutorials/importing-sequence-data/...`, which corresponds to the old name for this tutorial. The files that I'm adding here are in a new `2017.3/tutorials/importing` directory, which I think corresponds to our URL scheme for these data. Is that correct (in which case `2017.2/tutorials/import-sequence-data` would become `2017.3/tutorials/importing`)? 
This PR depends on https://github.com/qiime2/data.qiime2.org/pull/9
=> ENH: fixes #118

source/tutorials/atacama-soils.rst
Thirteen is clearly a better choice - the new interactive quality plots made it possible to determine that.
Here's the plot that I'm looking at. The position where the qualities jump in the beginning of each read direction is 13.
=> ENH: update trimming value based on review of new interactive quality plots

source/install/virtual/virtualbox.rst
Feel free to suggest alternative verbiage. This PR is necessitated by the changes proposed in https://github.com/qiime2/playbooks/pull/29, which mitigates the missing optical drive in VirtualBox by pre-installing the guest additions at image creation.
=> MAINT: Update VBox GA instructions

source/data-resources.rst
Fixes #135 
I `ag`ed for `2.0.5`, `2.0.6`, and `2017.2` --- this was the only relevant hit to come up.
=> BUG: Update QIIME 2 release in trained classifiers

requirements.txt
The pinned version of jinja2 (2.8) is incompatible with Emperor, which requires jinja2 >= 2.9.
=> MAINT: remove jinja2 version pin (2.8)

source/tutorials/fmt.rst, source/tutorials/moving-pictures.rst
I updated the `hint` in the FMT tutorial to not refer to a nonexistent note, and updated the Moving Pictures tutorial to reflect the fact that in the [new version of Emperor](https://github.com/qiime2/q2-emperor/pull/39#issuecomment-302795942) the 
> Axes are no longer labeled using numbers (0 (x %), 1 (y %), 2 (z %))
Fixes #149
I also searched all the other tutorials for mentions of "Emperor", "axis", or "axes" , and found nothing, so I think this PR should take care of any issues along those lines.
=> DOC: Update text for new Emperor

source/tutorials/feature-classifier.rst, source/tutorials/importing.rst
Code blocks with arguments of the variety 
> --type SomeAwesomeSemantic[Type]
fail, because of the `[` and `]`.  Instead, they should be of the form
> --type 'SomeAwesomeSemantic[Type]'
This PR fixes that problem.
=> BUG: Added literal (single) quotes around types with [

source/tutorials/importing.rst
With this PR, the importing tutorial now clarifies that both `fastq` and `fasts.gz` filetypes are supported for importing from the various `fastqManifestFormat`s.  Fixes #162
=> ENH: Mention that fastq supported in fastqmanifest

source/upgrade.rst
This PR adds a disclaimer to the AWS upgrade instructions informing the user to refer instead to the Linux (Native Installation) instructions if they did not use one of our official AMIs to build their AWS instance.
=> BUG: Fixes #164 for AWS upgrade

source/tutorials/metadata.rst
Also reworked some of the text for clarity, added more details in a few places, and fixed a typo.
Addresses part of #173.
=> ENH: update metadata format description to include comments, blank lines, and QIIME 1 support

source/data-resources.rst, source/install/index.rst, source/install/native.rst, source/install/virtual/docker.rst, source/install/virtual/virtualbox.rst, source/interfaces/q2studio.rst, source/tutorials/atacama-soils.rst, source/tutorials/exporting.rst, source/tutorials/feature-classifier.rst, source/tutorials/filtering.rst, source/tutorials/fmt.rst, source/tutorials/gneiss.rst, source/tutorials/importing.rst, source/tutorials/metadata.rst, source/tutorials/moving-pictures.rst
Updated:
- references to `2017.7` -> `2017.8`
- removed forum data links in favor of data.qiime2.org links
- updated scikit-learn version `0.18.2` -> `0.19.0`
- verified even sampling depth in Moving Pictures tutorial matches what is in
the text
- added `q2-sample-classifier` and `q2-longitudinal` to Core distribution list
=> MAINT: update to 2017.8

source/tutorials/index.rst, source/tutorials/longitudinal.rst
I've added a short tutorial demonstrating all actions currently in `q2-longitudinal`.
It is based on the tutorial on `q2-longitudinal` 's github page, but uses the moving pictures tutorial data instead.
The moving pictures dataset actually isn't great for q2-longitudinal, since the sample sizes are so small. We could just point to the tutorials on the github page instead, or port over the datasets that I use there.
=> added tutorial for q2-longitudinal

source/sphinx_extensions/plugin_directory/extension.py, source/sphinx_extensions/plugin_directory/templates/action.rst, source/sphinx_extensions/plugin_directory/templates/available.rst, source/sphinx_extensions/plugin_directory/templates/plugin.rst, source/theme/static/style.css
The plugin directory now displays CLI and Artifact API help text for actions instead of a custom table of inputs, parameters, and outputs (this table was generally confusing to users).
Thanks @thermokarst for having the idea of using the help text that's already being generated for the CLI and Artifact API! The code is much simpler now too :)
Also, instead of using an action's underscored name (`Action.id`), the action's CLI name (dashed) is used in URLs and content.
Indicates progress since it can take a little while to generate the plugin directory:
**Before:** https://docs.qiime2.org/2017.8/plugins/available/demux/emp_paired/
**After:** https://docs.qiime2.org/2017.9/plugins/available/demux/emp-paired/
:shipit:
=> ENH: plugin directory supports multiple interfaces

source/sphinx_extensions/plugin_directory/templates/plugin.rst
With the addition of pipeliens, an empty pipeline bullet showed up a lot on the `plugins/available/` page, so I made sections optional so that the toctree was a little cleaner. (This also helps out methods/visualizers)
=> MAINT: update plugin_directory for pipelines

source/plugins/future.rst
fixes #229 
Not sure if this page is even necessary any more — I replaced the link to the spreadsheet with a modified version of the note that is currently at the top of [that spreadsheet](https://docs.google.com/spreadsheets/d/1KdgbooDDuh_aE-aCGlVLNgMCli513wU9E5_PgpL6tbY/pubhtml?gid=0&single=true)
=> removed link to planned plugin spreadsheet from future plugins doc

source/tutorials/metadata.rst, source/tutorials/moving-pictures.rst
- Changed the word "fields" to "cells" (1 occurrence)
- Emphasized that the comment directive is optional
- Added tip about using `metadata tabulate` to view column types
- Updated Keemei URLs to the new canonical URL: https://keemei.qiime2.org
=> MAINT: misc minor updates to Metadata docs

source/tutorials/metadata.rst
The Metadata file format spec should be pretty complete at this point.
Here's the content that was added:
=> DOC: added "number formatting" and "advanced details" sections to Metadata file format spec

source/data-resources.rst
Looks like <http://greengenes.secondgenome.com/> isn't online anymore, so I've replaced it with a link to the two main papers describing the greengenes database.
Feedback welcome! Like, is there a better way to include citations?
=> replace dead link on data-resources.rst

requirements.txt, source/conf.py, source/sphinx_extensions/plugin_directory/extension.py, source/sphinx_extensions/plugin_directory/templates/action.rst, source/sphinx_extensions/plugin_directory/templates/plugin.rst, source/theme/static/style.css
**(copied the registration, in practice plot wouldn't really have its own citations)**
=> ENH: more citations in docs

source/plugins/developing.rst
Okay, take 2 - this should be what we want! Simply add the link to the new developer documentation to the top of the "Developing a QIIME 2 plugin" page.
=> Add link to dev docs in developing.rst

source/sphinx_extensions/plugin_directory/extension.py, source/sphinx_extensions/plugin_directory/templates/action.rst, source/sphinx_extensions/plugin_directory/templates/plugin.rst
fixes #307
Two aesthetic questions for discussion:
It is possible to add copy-to-clipboard buttons to both plugin- and action-page pre tags. I opted not to do so, because they felt cluttered, and I'm not convinced that copy-buttons bring much value in this context. 
**Compare:** 
On Action pages, I wanted parity in the look of the CLI and API tabs, so I added an "Invocation" block to the CLI tab to mirror the "Import" block in the API tab. The new "Invocation" block duplicates the usage text in the docstring, which looks a bit sloppy to me. 
We can: 
- Merge as is, retaining the content duplication (result: screencaps below, pro: quick/easy, con: duplication)
- Remove the "Invocation" block from the CLI tab (pro: quick/easy, con: loss of parity)
- Remove the "Usage" line from the CLI …
=> BUG: added import and invocation to action and plugin pages

source/_static/clipboard-driver.js, source/sphinx_extensions/plugin_directory/templates/action.rst, source/sphinx_extensions/plugin_directory/templates/plugin.rst
The command block directive is trying to run a shell command. Just add the `:no-exec:` directive argument to prevent that issue.
(Also fixed indentation)
=> BUG: fix python command-block to no-exec

source/sphinx_extensions/plugin_directory/templates/plugin.rst
Tested locally with `make html`, this builds without error (well, tested up to the tutorials, then terminated the build).
=> BUG: One more no-exec on the rendered help text

source/tutorials/feature-classifier.rst
=> feature-classifier tutorial: clarify that reference seqs and taxonomy should be paired

source/tutorials/sample-classifier.rst
This PR adds text modifications requested by @gregcaporaso after merging #333 (I have requested @gregcaporaso to review these sections)
Also adds some other tweaks to the text:
1. links to scikit-learn documentation for more details on RFE, estimators, and feature importance calculations.
2. Added a "pitfalls" type section describing practices that should be avoided. (@BenKaehler has agreed to review this section)
=> ENH: additions to q2-sample-classifier tutorial, added pitfalls section

source/tutorials/longitudinal.rst, source/tutorials/sample-classifier.rst
Just swaps the section to the longitudinal tutorial.
A download link was added for the ecam table, inter-tutorial links removed, since the content referenced is on the same page, and the metadata input file was renamed to match the rest of the tutorial.
I'm pretty sure this should work...
=> MAINT: move maturity-index tutorial

source/tutorials/gneiss.rst
=> BUG: hierarchy overwritten in gneiss tutorial

source/tutorials/gneiss.rst
Command block was never executed (missing preceding newline) so we didn't realize that rooted-tree.qza doesn't exist, it's easier to just drop for now.
=> HACK: drop ilr-phylogenetic from gneiss tutorial

.travis.yml, README.md, source/tutorials/fmt-cdiff.rst, source/tutorials/index.rst
=> adding fmt tutorial

source/tutorials/longitudinal.rst
To avoid stochastic splitting errors during regression
=> longitudinal tutorial: set random state and stratify maturity-index

source/tutorials/fmt-cdiff.rst
Beta group significance results from the alpha/beta core diversity section are identical but the output filenames suggest otherwise. On closer inspection, it looks as though the filename was updated in one of the commands but the specific metadata category used did not get updated.
=> Copypasta error on beta-group-significance

source/tutorials/longitudinal.rst, source/tutorials/sample-classifier.rst
now all commands have random seeds specified.
fixes #366 
Also set a different seed for q2-feature-volatility — the original command ran but was making an excessively large viz that would not display volatility plots on some machines.
=> set random seeds in q2-sample-classifier and q2-longitudinal tutorials

requirements.txt, source/sphinx_extensions/command_block/extension.py, source/sphinx_extensions/plugin_directory/extension.py, source/sphinx_extensions/plugin_directory/templates/action.rst, source/sphinx_extensions/plugin_directory/templates/plugin.rst, source/sphinx_extensions/qiime1.py, source/sphinx_extensions/question.py
Sphinx 2.0 recently landed --- this changeset updates the user docs to work with the latest (and greatest). Most of the changes have to do with our custom admonitions, and some deprecated APIs. Also, I had to update the bibtex render style to something other than the default, which is a set of paragraph elements. Paragraphs get cross-references in Sphinx --- this causes the build to fail because there are no corresponding citations in the docs anywhere. My solution was to change to a bullet list, since those elements don't get the cross-reference treatment!
=> MAINT: Sphinx 2.0

source/tutorials/pd-mice.rst
@thermokarst @jwdebelius 
1. fixed some typos and some unclear sentences.
2. note: the use of first-distances previously looked at rate of change, not difference from day 7 (as was indicated in the text). I added the `baseline` parameter so that the command conforms to the text — but if you prefer to look at rate of change pls revert that command and modify the text instead.
3. I moved the taxonomy classification section until after diversity. This matches what we will do in the workshop, and makes a bit more sense (phylogeny happens next to diversity, and taxonomy happens next to barcharts).
4. I added a short q2-sample-classifier demo to the end of the tutorial. This is my new favorite tutorial dataset for sample classifiers, though it is no good for regression (so we may still need to …
=> text tweaks plus sample classifier

source/data-resources.rst
Rebuilt classifiers in latest version, because v21.2 fixes a bug introduced in v0.21, and present in v0.21.1.
Not pinning version number in `q2-feature-classifier` unless [`{{ pin_compatible('scikit-learn', exact=True) }}`](https://github.com/qiime2/q2-feature-classifier/commit/e920493139c04abcc92e0ad5c4ea18e0e7971d68) fails to work as expected.
=> DEP:Updates sk-learn data-resources to v0.21.2

source/sphinx_extensions/command_block/extension.py
With the addition of IO capturing, we lost the ability to run multiple commands in a single block. This broke a few tutorials which groups commands in a single logical block.
Fixing the early return and limiting IO capture to a single command per block seems to do the trick.
=> BUG: fix multi-command command-blocks

LICENSE, source/conf.py, source/sphinx_extensions/__init__.py, source/sphinx_extensions/checkpoint.py, source/sphinx_extensions/command_block/__init__.py, source/sphinx_extensions/command_block/extension.py, source/sphinx_extensions/external_links.py, source/sphinx_extensions/plugin_directory/__init__.py, source/sphinx_extensions/plugin_directory/extension.py, source/sphinx_extensions/qiime1.py, source/sphinx_extensions/question.py
Updated copyright headers, and `copyright` variable in `conf.py`, to reflect current year.
=> MAINT: Update copyright headers to 2020

source/tutorials/longitudinal.rst
It looks like the only plot that mentions the vega editor in its doc text is `longitudinal volatility`. This PR adds a note about that feature being temporarily disabled pending a rework of this plot and others to work properly with Vega 5.
=> HACK: Add note about vega, revert later

source/data-resources.rst
I trained new classifiers for the 2020.6 release, there are several significant changes reflected in this docs PR:
1. added SILVA 138 (old classifiers were release 132)
2. added formatted SILVA 138 files to this page (so users can train their own classifiers)
3. added citation info to this doc (used RESCRIPt to format and train/test classifiers, also remind users to cite SILVA/GG and q2-feature-classifier)
4. added links to SILVA/GG license info
5. updated to scikit-learn 0.23.1 (latest release as of writing)
=> add silva 138 links and citations to data-resources

source/tutorials/qiime2-for-experienced-microbiome-researchers.rst, source/tutorials/read-joining.rst
This first commit only changes the method in the command block to see if it fixes the issue. Assuming my understanding is correct and that's where the code that's run is from.
=> MAINT: Change tutorials from q-score-joined to q-score

requirements.txt
restricted Sphinx version to between 3.0 and 4.0
=> maint: excluded recent major Sphinx version

source/citation.rst
Our [citation page](https://docs.qiime2.org/2021.4/citation/) correctly displays the Nature citation, but links to the PeerJ preprint. If this isn't intentional, this PR should fix the inconsistency.
=> Changes "preprint" to "paper", updates URL

source/interfaces/q2studio.rst
Issue reported via forum: https://forum.qiime2.org/t/instaling-quiime-2-studio-error/19886
Similar issue resolved with the same updates: https://github.com/qiime2/vm-playbooks/commit/f5c2f507d7c479263bf9bdc68aa93a6e894a05ab
=> BUG: q2studio installation instructions - resolving npm install dependency conflicts

source/data-resources.rst
Just some little tweaks to the data-resources page:
* added citation for the RESCRIPt pre-print (currently cites the zenodo doi linked to the GH repo).
* Also slightly adjusted the description and references for the weighted classifiers to indicate (a) that they are not only V4 but they are 16S, and (b) to also cite the references listed for the unweighted classifiers.
=> update references re: rescript

source/tutorials/sample-classifier.rst
Added section describing new output of `classify_samples`, namely `SampleData[TrueTargets]` artifacts added in [this PR](https://github.com/qiime2/q2-sample-classifier/pull/204)
=> MAINT: tutorial update q2-sample-classifier

source/tutorials/phylogeny.rst
@nick-youngblut reported on [the forum](https://forum.qiime2.org/t/q2-alignment-reference-based-alignment-using-sina/6220/3?u=nicholas_bokulich) that SINA is no longer supported in q2-alignment, but a community tutorial for this deprecated action is still described in the QIIME 2 documentation.
This PR fixes this issue by:
1. removing the link to the now-archived tutorial 
2. instead ports over the relevant text describing the advantages of reference-based alignment
3. briefly describes how reference-based alignments can be imported into QIIME 2
Thanks @nick-youngblut for reporting this documentation lapse!
=> drop link to sina community tutorial

source/install/native.rst
The code blocks mixed in with text in our install instructions are a bit confusing and can lead to accidental copying of the text in addition to just the install commands. I made some small tweaks to the HTML block that I think will improve readability.
Here is what the install code block per OS **currently** looks like for conda installation:
**OSX**:
**WSL**:
And here is what these code blocks will look like (tested and rendered locally) when the text is separated from the actual commands:
**OSX**:
**WSL**:
I couldn't find a way to include the copy widget in this block due to the fact that this isn't just a raw code block - it's HTML, which accommodates the multiple panes per OS. If anyone knows of a way to add in the copy widget, please feel free to add that in!
=> IMP: updating conda installation code block to separate install and cleanup commands

source/install/native.rst
This PR adds an install tab with instructions for macOS users with an M1 chip.
=> imp: adding M1 chip macOS install instructions

source/install/native.rst, source/install/virtual/wsl.rst
Updates the native installation docs to not disregard M2 apple silicon users. Also updates the WSL instructions to unify the usage of the WSL acronym from elsewhere in the docs.
---
---
=> maint: native installation instructions hints

source/data-resources.rst
In this pull request, we revise the entries surrounding Greengenes and in particular note 2022.10, which is the latest release of Greengenes2.
cc @gregcaporaso
=> Greengenes database updates

source/data-resources.rst
This PR fixes a broken reference to previous versions of the Greengenes classifiers, and adds a note in several places related to the species-level taxonomy assignments in our classifiers. 
These are two independent commits, so don't need to be squashed before merge.
=> updates notes about classifiers on data resources page

source/tutorials/importing.rst
Closes: [#713](https://github.com/qiime2/qiime2/issues/713) and #558
=> Updates to importing tutorial

source/install/native.rst
removes mamba from the QIIME 2 install docs now that conda's primary solver uses libmamba.
=> MAINT: remove mamba from install docs

source/plugins/developing.rst
Both q2-emperor and q2-diversity have transitioned their CI.
=> Travis-CI -> GitHub Actions in plugin docs

source/conf.py
the base URL [that is being used to generate the artifact links](https://github.com/qiime2/sphinx-ext-qiime2/blob/82f9072d6baa07f91466638c1fa0378790df5be4/q2doc/usage/driver.py#L37) in the MP usage tutorial was never updated in the 2022.2 release (PR xref [here](https://github.com/qiime2/docs/pull/527)). the way i've dev bumped subsequent releases has just been a find/replace for n-1 release -> current release, so this got missed for two years. this surfaced because of [this forum post](https://forum.qiime2.org/t/moving-picture-tutorial-ancom-bc-results-broken-links/30480) from Luca, pointing out that the ancombc links don't work (which makes sense b/c that functionality didn't exist in 2021.11). in any case- this shouldn't come up again with my current process, but i'd like to find a way …
=> BUG: usage links using wrong release in base URL

source/install/native.rst
URLs can now be used in the `-f` param of `conda env create`. Replacing a local file download with a direct raw GH link should reduce the amount of install errors users run into by:
- removing the need to use `wget`
- removing the possibility that users download differing files with the same name (i.e. if a release env gets patched, the file name remains the same) and then aren't using the correct file for install
This adjustment reduces the number of steps required for install and creates a more concise process.
=> IMP: install instructions use direct URL for env file

source/data-resources.rst, source/tutorials/moving-pictures-usage.rst, source/tutorials/moving-pictures.rst, source/tutorials/pd-mice.rst
paired with https://github.com/qiime2/data302/pull/155
=> MAINT: Update old classifier URLs

.github/workflows/ci.yml, source/conf.py, source/data-resources.rst, source/install/index.rst, source/install/native.rst, source/install/virtual/docker.rst, source/tutorials/atacama-soils.rst, source/tutorials/chimera.rst, source/tutorials/exporting.rst, source/tutorials/feature-classifier.rst, source/tutorials/filtering.rst, source/tutorials/fmt.rst, source/tutorials/importing.rst, source/tutorials/longitudinal.rst, source/tutorials/metadata.rst, source/tutorials/moving-pictures-usage.rst, source/tutorials/moving-pictures.rst, source/tutorials/otu-clustering.rst, source/tutorials/overview.rst, source/tutorials/pd-mice.rst, source/tutorials/phylogeny.rst, source/tutorials/qiime2-for-experienced-microbiome-researchers.rst, source/tutorials/quality-control.rst, source/tutorials/read-joining.rst, source/tutorials/sample-classifier.rst, source/tutorials/utilities.rst
~~**NOTE**: the python version will need to change if we update to 3.11 in the next release.~~ disregard, python version isn't slated for update in 2025.4
=> DEV-BUMP: 2025.4

source/install/index.rst
Reverts qiime2/docs#594. This is no longer needed as we're transitioning to the [new docs](https://amplicon-docs.qiime2.org) for 2025.4.
=> revert update to 2025.4

.github/workflows/ci.yml, source/conf.py, source/data-resources.rst, source/install/native.rst, source/install/virtual/docker.rst, source/tutorials/atacama-soils.rst, source/tutorials/chimera.rst, source/tutorials/exporting.rst, source/tutorials/feature-classifier.rst, source/tutorials/filtering.rst, source/tutorials/fmt.rst, source/tutorials/importing.rst, source/tutorials/longitudinal.rst, source/tutorials/metadata.rst, source/tutorials/moving-pictures-usage.rst, source/tutorials/moving-pictures.rst, source/tutorials/otu-clustering.rst, source/tutorials/overview.rst, source/tutorials/pd-mice.rst, source/tutorials/phylogeny.rst, source/tutorials/qiime2-for-experienced-microbiome-researchers.rst, source/tutorials/quality-control.rst, source/tutorials/read-joining.rst, source/tutorials/sample-classifier.rst, source/tutorials/utilities.rst
Reverts qiime2/docs#593. This is no longer needed as we're transitioning to the [new docs](https://amplicon-docs.qiime2.org) for 2025.4.
=> revert dev bump to 2025.4
